### ISSUE TITLE
Иконки не отображаются в списке выбора иконок

### ISSUE THREAD

**Issue by jonyrh** [iswitch/ha-yandex-icons#14]
Добрый день!

При ручной вставке имени иконки - она появляется, но в списке их нет, так и должно быть?

В ресурсах пробовал указывать тип `module` и url `/hacsfiles/ha-yandex-icons/yandex-icons.js` и `/local/community/ha-yandex-icons/yandex-icons.js`, в конфиг `configuration.yaml` добавил 
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/ha-yandex-icons/yandex-icons.js
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```
![image](https://github.com/iswitch/ha-yandex-icons/assets/28771126/16fc6ca4-e36f-443c-a762-1be6a3eb6540)
